RF-23725 Support new cancel/cancel-all values for conflict parameter
Continue supporting legacy abort/abort-all values for now.

diff --git a/src/commands/run_qa.yml b/src/commands/run_qa.yml
--- a/src/commands/run_qa.yml
+++ b/src/commands/run_qa.yml
@@ -21,7 +21,7 @@ parameters:
     default: ""
 
   conflict:
-    description: How other currently in-progress runs should be handled. Values are `abort` to abort runs in the same environment as your new run and `abort-all` to abort all runs
+    description: How other currently in-progress runs should be handled. Values are `cancel` to cancel runs in the same environment as your new run and `cancel-all` to cancel all runs
     type: string
     default: ""
 
@@ -74,8 +74,8 @@ steps:
 
         # Validate conflict
         if [ -n "<< parameters.conflict >>" ] ; then
-          if ! echo "abort abort-all" | grep -Eq "\b"<< parameters.conflict >>"\b" ; then
-            echo "Error: << parameters.conflict >> not in (abort abort-all)"
+          if ! echo "cancel cancel-all abort abort-all" | grep -Eq "\b"<< parameters.conflict >>"\b" ; then
+            echo "Error: << parameters.conflict >> not in (cancel cancel-all)"
             exit 1
           fi
         fi
